MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: "pretrain/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
DATASETS:
  SOURCE_TRAIN: "gta5_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
  TT: "cityscapes_TT_train"
  II: "cityscapes_II_train"
INPUT:
  TARGET_INPUT_SIZE_TRAIN: (1024, 512)
  INPUT_SCALES_TRAIN: (0.75, 1.25)
  INPUT_SIZE_TEST: (1536, 768)
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.2
DTU:
  DYNAMIC: False
  Query_STEP: 3
  Query_START: 9
  META_MAX_UPDATE: 30
  EMA_WEIGHT: 0.99
  PROXY_METRIC: 'Soft_ND'
  FIX_ITERATION: 12
TCR:
  OPEN: True
  TOPK_CANDIDATE: 0.5
  UPDATE_FREQUENCY: 3000
METAPL:
  OPEN: False
  VAL_UPDATE: 1000
  TOP_K: 0.25
SOLVER:
  BASE_LR: 2.5e-4
  MAX_ITER: 62500
  STOP_ITER: 7000
  BATCH_SIZE: 4
  CHECKPOINT_PERIOD: 500
